# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from grpc_router.stubs import grpc_router_service_pb2 as grpc__router_dot_stubs_dot_grpc__router__service__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in grpc_router/stubs/grpc_router_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GRPCRouterServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterService = channel.unary_unary(
                '/grpcrouter.GRPCRouterService/RegisterService',
                request_serializer=grpc__router_dot_stubs_dot_grpc__router__service__pb2.ServiceRegistrationRequest.SerializeToString,
                response_deserializer=grpc__router_dot_stubs_dot_grpc__router__service__pb2.ServiceRegistrationResponse.FromString,
                _registered_method=True)
        self.DeregisterService = channel.unary_unary(
                '/grpcrouter.GRPCRouterService/DeregisterService',
                request_serializer=grpc__router_dot_stubs_dot_grpc__router__service__pb2.ServiceDeregistrationRequest.SerializeToString,
                response_deserializer=grpc__router_dot_stubs_dot_grpc__router__service__pb2.ServiceDeregistrationResponse.FromString,
                _registered_method=True)


class GRPCRouterServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeregisterService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GRPCRouterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterService': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterService,
                    request_deserializer=grpc__router_dot_stubs_dot_grpc__router__service__pb2.ServiceRegistrationRequest.FromString,
                    response_serializer=grpc__router_dot_stubs_dot_grpc__router__service__pb2.ServiceRegistrationResponse.SerializeToString,
            ),
            'DeregisterService': grpc.unary_unary_rpc_method_handler(
                    servicer.DeregisterService,
                    request_deserializer=grpc__router_dot_stubs_dot_grpc__router__service__pb2.ServiceDeregistrationRequest.FromString,
                    response_serializer=grpc__router_dot_stubs_dot_grpc__router__service__pb2.ServiceDeregistrationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpcrouter.GRPCRouterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('grpcrouter.GRPCRouterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GRPCRouterService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpcrouter.GRPCRouterService/RegisterService',
            grpc__router_dot_stubs_dot_grpc__router__service__pb2.ServiceRegistrationRequest.SerializeToString,
            grpc__router_dot_stubs_dot_grpc__router__service__pb2.ServiceRegistrationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeregisterService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpcrouter.GRPCRouterService/DeregisterService',
            grpc__router_dot_stubs_dot_grpc__router__service__pb2.ServiceDeregistrationRequest.SerializeToString,
            grpc__router_dot_stubs_dot_grpc__router__service__pb2.ServiceDeregistrationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
